---
# reference https://github.com/coopnorge/cloud-platform-apis/blob/main/cloud-platform-apis/templates/repositoryconfig.github.coop.no/definition.yaml
# status of this repository: https://argocd.internal.coop/applications?search=pallet-github-workflow-release-tagger-for-github-workflows&showFavorites=false&proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=
apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: repository-config
spec:
  description: In GitHub actions, the major version tags should be automatically updated when there is a new release so that major version referenced in workflows can use the latest version.
  branches:
    default: main
    protection:
    - id: main
      pattern: main
      requiredStatusChecks:
        checks:
        - "kubernetes-ci-check"
        - "policy-bot: main"
